spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
  
  jpa:
    show-sql: true
    hibernate:        ddl-auto: update
    properties:        hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
  security:
    oauth2:
      client:
        registration:          google:
            client-id: 1076073845067-0l73p5ag8kfrkp36d64nrnh0eqnesq0a.apps.googleusercontent.com
            client-secret: 2-ZO7a8cOyiVQcuSH__L7qcK
            scope:            - email
            - profile

app:
  auth:
    tokenSecret: donggu
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect